// Generated by Supabase CLI from the local public schema. Do not edit.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {

  "public": {
          Tables: {
            "menu_items": {
                  Row: {
                    "archived_at": string | null,"created_at": string,"currency": string,"description": string,"id": string,"is_available": boolean,"is_published": boolean,"name": string,"price_centavos": number,"store_id": string,"updated_at": string
                  }
                  Insert: {
                    "archived_at"?: string | null,"created_at"?: string,"currency"?: string,"description"?: string,"id"?: string,"is_available"?: boolean,"is_published"?: boolean,"name": string,"price_centavos": number,"store_id": string,"updated_at"?: string
                  }
                  Update: {
                    "archived_at"?: string | null,"created_at"?: string,"currency"?: string,"description"?: string,"id"?: string,"is_available"?: boolean,"is_published"?: boolean,"name"?: string,"price_centavos"?: number,"store_id"?: string,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "menu_items_store_id_fkey"
      columns: ["store_id"]
isOneToOne: false
      referencedRelation: "stores"
      referencedColumns: ["id"]
    }
                  ]
                },"profiles": {
                  Row: {
                    "account_status": Database["public"]['Enums']["account_status"],"contact_phone": string | null,"created_at": string,"display_name": string,"id": string,"updated_at": string
                  }
                  Insert: {
                    "account_status"?: Database["public"]['Enums']["account_status"],"contact_phone"?: string | null,"created_at"?: string,"display_name"?: string,"id": string,"updated_at"?: string
                  }
                  Update: {
                    "account_status"?: Database["public"]['Enums']["account_status"],"contact_phone"?: string | null,"created_at"?: string,"display_name"?: string,"id"?: string,"updated_at"?: string
                  }
                  Relationships: [

                  ]
                },"store_memberships": {
                  Row: {
                    "created_at": string,"is_active": boolean,"role": Database["public"]['Enums']["store_role"],"store_id": string,"updated_at": string,"user_id": string
                  }
                  Insert: {
                    "created_at"?: string,"is_active"?: boolean,"role": Database["public"]['Enums']["store_role"],"store_id": string,"updated_at"?: string,"user_id": string
                  }
                  Update: {
                    "created_at"?: string,"is_active"?: boolean,"role"?: Database["public"]['Enums']["store_role"],"store_id"?: string,"updated_at"?: string,"user_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "store_memberships_store_id_fkey"
      columns: ["store_id"]
isOneToOne: false
      referencedRelation: "stores"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "store_memberships_user_id_fkey"
      columns: ["user_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"stores": {
                  Row: {
                    "address_text": string,"approval_status": Database["public"]['Enums']["store_approval_status"],"archived_at": string | null,"barangay": string,"created_at": string,"delivery_enabled": boolean,"description": string,"id": string,"location": unknown,"name": string,"public_phone": string | null,"slug": string,"updated_at": string
                  }
                  Insert: {
                    "address_text": string,"approval_status"?: Database["public"]['Enums']["store_approval_status"],"archived_at"?: string | null,"barangay"?: string,"created_at"?: string,"delivery_enabled"?: boolean,"description"?: string,"id"?: string,"location"?: unknown,"name": string,"public_phone"?: string | null,"slug": string,"updated_at"?: string
                  }
                  Update: {
                    "address_text"?: string,"approval_status"?: Database["public"]['Enums']["store_approval_status"],"archived_at"?: string | null,"barangay"?: string,"created_at"?: string,"delivery_enabled"?: boolean,"description"?: string,"id"?: string,"location"?: unknown,"name"?: string,"public_phone"?: string | null,"slug"?: string,"updated_at"?: string
                  }
                  Relationships: [

                  ]
                }
          }
          Views: {
            [_ in never]: never
          }
          Functions: {
            "admin_create_store":
{ Args: { "owner_user": string,"store_address": string,"store_name": string,"store_slug": string }; Returns: string
                           },
"admin_set_account_status":
{ Args: { "new_status": Database["public"]['Enums']["account_status"],"target_user": string }; Returns: undefined
                           },
"admin_set_platform_role":
{ Args: { "enabled": boolean,"target_role": Database["public"]['Enums']["platform_role"],"target_user": string }; Returns: undefined
                           },
"admin_set_store_approval":
{ Args: { "new_status": Database["public"]['Enums']["store_approval_status"],"target_store": string }; Returns: undefined
                           },
"admin_set_store_archived":
{ Args: { "archived": boolean,"target_store": string }; Returns: undefined
                           },
"admin_set_store_membership":
{ Args: { "active": boolean,"new_role": Database["public"]['Enums']["store_role"],"target_store": string,"target_user": string }; Returns: undefined
                           },
"get_my_application_roles":
{ Args: Record<PropertyKey, never>; Returns: (string)[]
                           }
          }
          Enums: {
            "account_status": "active"|"suspended","platform_role": "admin"|"rider","store_approval_status": "pending"|"approved"|"rejected","store_role": "owner"|"manager"|"staff"
          }
          CompositeTypes: {
            [_ in never]: never
          }
        }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
  ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
      Row: infer R
    }
    ? R
    : never
  : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
      Insert: infer I
    }
    ? I
    : never
  : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
      Update: infer U
    }
    ? U
    : never
  : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
  ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
  : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never
> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
  ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
  : never

export const Constants = {
  "public": {
          Enums: {
            "account_status": ["active", "suspended"],"platform_role": ["admin", "rider"],"store_approval_status": ["pending", "approved", "rejected"],"store_role": ["owner", "manager", "staff"]
          }
        }
} as const
